### PR TITLE
Add an offset option and correct Avery7160 margin

### PR DESCRIPTION
**Pull request by peakman**
Add the offset option to offset text within each cell.  See README for an example.

Update types.yaml by adding a bottom margin for Avery7160.

### CODE REVIEW

**Comment by jordanbyron** [comment]
Hey @peakman!

Thanks for the PR. I don't think this is a feature we need to support as there is already a way to add an offset without extending the library:

```ruby
names    = ["Jordan", "Chris", "Jon", "Mike"]
pdf_path = "test/pdfs/offset_option.pdf"
offset_x = 10
offset_y = 10

Prawn::Labels.generate(pdf_path, names, type: "Avery5160") do |pdf, name|
  x, y = pdf.bounds.top_left

  # Add an offset to every label
  pdf.bounding_box([x + offset_x, y - offset_y],
                   width:  pdf.bounds.width - offset_x,
                   height: pdf.bounds.height - offset_y) do
    pdf.text name
  end
end
```

If you send over another pull request with just the Avery7160 change I'd be happy to merge it. :fire_engine:

**Comment by peakman** [comment]
Your solution meets my immediate needs.  Thanks.

I can still see some value in having an offset option as part of the library - though not with the implementation I proposed.  The advantage is that (with a little work) it could be made to apply also to vertical text and shrink to fit. (I think I'm correct in saying that your solution will not work reliably with either?)

**Comment by jordanbyron** [comment]
> (I think I'm correct in saying that your solution will not work reliably with either?)

I don't know you'd have to try running my example code with those options turned on. shrink to fit's [implementation](https://github.com/jordanbyron/prawn-labels/blob/master/lib/prawn/labels.rb#L119-L133) feels a bit hacky to me so I wouldn't be surprised if it broke easily.

**Comment by peakman** [comment]
You're correct.  I modified the test suite to run tests with offsets.  Vertical text offsets worked fine.
Shrink to fit was OK as long as the shrunken text could still fit within the reduced bounding box.  When it didn't things went crazy.

See attachments.

[vertical_labels_with_offset.pdf](https://github.com/jordanbyron/prawn-labels/files/49062/vertical_labels_with_offset.pdf)

[shrink_to_fit_with_offset.pdf](https://github.com/jordanbyron/prawn-labels/files/49064/shrink_to_fit_with_offset.pdf)

**Pull request closed without merging**
